server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionRouteLocator: INFO
    root: INFO


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -   id: discovery-server
            filters:
              - SetPath=/
            predicates:
              - Path=/eureka/web
            uri: http://localhost:8761
        -   id: discovery-server-static
            predicates:
              - Path=/eureka/**
            uri: http://localhost:8761
        -   id: cart-service
            filters:
              - RewritePath=/api/v1/cart/v3/api-docs, /v3/api-docs
            predicates:
              - Path=/api/v1/cart/**
            uri: lb://cart-service
        -   id: manage-items-service
            filters:
              - RewritePath=/api/v1/item/v3/api-docs, /v3/api-docs
            predicates:
              - Path=/api/v1/item/**
            uri: lb://manage-items-service
        -   id: auth-service
            filters:
              - RewritePath=/api/v1/auth/v3/api-docs, /v3/api-docs
            predicates:
              - Path=/api/v1/auth/**
            uri: lb://auth-service
        -   id: openapi
            filters:
              - RewritePath=/v3/api-docs/(?<segment>.*), /${segment}/v3/api-docs
            predicates:
              - Path=/v3/api-docs/**
            uri: http://localhost:${server.port}
springdoc:
  swagger-ui:
    urls:
      -   name: Cart Service APIs
          url: /v3/api-docs/api/v1/cart
      -   name: Manage Items Service APIs
          url: /v3/api-docs/api/v1/item
      -   name: Auth Service APIs
          url: /v3/api-docs/api/v1/auth